---
title: "Estudio de la homogeneidad de la infección para los datos de España"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---


<!-- Después de la lectura 37 Estudio de la homogeneidad de la infección -->

## Instrucciones
En esta tarea vamos a realizar un estudio de la homogeneización de la infección por comunidades autónomas dentro de España.
Es decir, a partir del test $\chi^2$ vamos a ver si el virus se expandió por igual en todas las comunidades autónomas de España.


## Descripción de la tarea

Instrucciones de tareas

En el recurso descargable ficheros.zip tenéis dos ficheros:

- El archivo `datosCCAA.csv` donde estan los datos del número de infectados, hospitalizados, fallecidos y pacientes en las UCI (ver la variable o columna tipo) de las 17 comunidades autónomas (faltan Ceuta y Melilla) de España.

- El archivo `Fichero_poblaciónCCAA.csv` donde están los datos de la población o del número de habitantes de las 17 comunidades autónomas.

### Pregunta 1


En primer lugar, usando la función `select` del paquete `tidyverse`, transformar la tabla de datos anterior en una tabla de datos donde la primera columna sea la fecha, y a partir de la segunda columna hasta la última aparezcan el número de infectados de cada comunidad autónoma. Es decir debería aparecer una estructura como la que sigue:

fecha tipo Andalucía Aragón Asturias Baleares Canarias Cantabria `Castilla-La Ma… `Castilla y Leó… Cataluña

<date> <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>

1 2020-02-27 casos 1 0 0 1 6 0 0 0 2

2 2020-02-28 casos 6 1 0 1 6 0 0 2 3

3 2020-02-29 casos 8 1 0 2 6 0 0 2 5

4 2020-03-01 casos 12 0 1 2 7 1 1 3 6

5 2020-03-02 casos 12 0 1 2 7 10 3 3 15

6 2020-03-03 casos 13 0 1 2 7 10 7 8 15

donde faltan 7 columnas más correspondientes a las comunidades autónomas de Valencia, Extremadura, Galicia, Madrid, Murcia, Navarra y País Vasco.


Indicación:  primero filtrar los datos seleccionando las variables de interés y en un segundo filtrado, usar la opción `pivot_wider` para obtener lo que se pide.

### Pregunta 2

Usando el paquete `ggplot2`, realizar un gráfico del número de infectados donde cada comunidad autónoma aparezca de un color distinto.

### Pregunta 3

Para el día **15 de marzo de 2020** y suponiendo que la infección se ha expandido por igual en todas las comunidades autónomas hallar el **número de infectados esperado y empírico** para todas las comunidades autónomas.

### Pregunta 4

Realizar el test $\chi^2$ correspondiente para testear si nuestra hipótesis de infección por igual es cierta o no y comentar los resultados obtenidos.

### Pregunta 5

Realizar las preguntas 3) y 4) pero para el **día 4 de abril.**

### Pregunta 6

Realizar las preguntas 1), 2), 3) y 4) pero en lugar de considerar el número de infectados, considerar el **número de fallecidos.**

### Pregunta 7

Realizar las preguntas 1), 2), 3) y 4) pero en lugar de considerar el número de infectados, considerar el **número de hospitalizados.**